Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
File "./theories/Programming/Show.v", line 64, characters 2-37:
Warning: Declaring a scope implicitly is deprecated; use in advance an
explicit "Declare Scope show_scope.". [undeclared-scope,deprecated]
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14f7f07f7820> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14e2181f8d30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14aa975b8790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14fef2c17700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:6 out of the last 6 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14e212e45ca0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14d8bf2caf70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 41 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14a8542991f0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:6 out of the last 6 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14ff0ad5e790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14e2ebdcadc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 42 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14a853047d30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14b6c250fd30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14d8aac365e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 11 calls to <function ModelWrapper.get_set_def_fn.<locals>.set_def_fn at 0x151c00814dc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14e2e90d7430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 241 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14acbdac0c10> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 253 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x1540dc156040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14b6a3cdbca0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 13 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14acd4a0e5e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 11 calls to <function ModelWrapper.get_set_def_fn.<locals>.set_def_fn at 0x153e822b3af0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 43 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x145648f20430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
WARNING:tensorflow:5 out of the last 5 calls to <function ModelWrapper.get_predict_fn.<locals>.pred_fn at 0x14ec14ecdee0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.uCMhUr/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
