File "./theories/Init/Logic.v", line 233, characters 2-55:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Bool/Bool.v", line 42, characters 2-15:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Classes/CMorphisms.v", line 271, characters 4-20:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Logic/Decidable.v", line 186, characters 0-17:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/NatInt/NZSqrt.v", line 49, characters 1-13:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/Integer/Abstract/ZDivTrunc.v", line 406, characters 0-7:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/NatInt/NZLog.v", line 880, characters 1-18:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Sets/Multiset.v", line 65, characters 4-43:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetGenTree.v", line 397, characters 1-42:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Lists/SetoidList.v", line 179, characters 1-37:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/PArith/Pnat.v", line 55, characters 1-21:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Structures/OrderedType.v", line 135, characters 64-70:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/micromega/EnvRing.v", line 548, characters 2-64:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Logic/WKL.v", line 158, characters 0-27:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Logic/Diaconescu.v", line 88, characters 1-84:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/micromega/RingMicromega.v", line 653, characters 0-18:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/QArith/Qcabs.v", line 24, characters 7-45:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FSetEqProperties.v", line 87, characters 0-14:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetEqProperties.v", line 93, characters 0-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/DecimalN.v", line 29, characters 1-37:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetFacts.v", line 479, characters 0-31:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Raxioms.v", line 427, characters 2-9:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Classes/RelationPairs.v", line 143, characters 9-20:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FSetToFiniteSet.v", line 104, characters 1-38:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Logic/Epsilon.v", line 28, characters 2-56:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/Cyclic/Abstract/CyclicAxioms.v", line 264, characters 1-37:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/Cyclic/Int63/Cyclic63.v", line 122, characters 1-165:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/nsatz/Nsatz.v", line 178, characters 1-27:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ranalysis1.v", line 549, characters 2-32:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rseries.v", line 413, characters 0-60:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/R_sqrt.v", line 88, characters 2-159:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Exp_prop.v", line 82, characters 2-37:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rgeom.v", line 153, characters 2-550:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Cauchy_prod.v", line 34, characters 2-9:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EINTR, "waitpid", "")."
Please report at http://coq.inria.fr/bugs/.

Thread 1 killed on uncaught exception Failure("Embedding.generateEmbedding: Failed: This vat has no restorer")
Raised at Lwt.Miscellaneous.poll in file "src/core/lwt.ml", line 3072, characters 20-29
Called from Lwt_main.run.run_loop in file "src/unix/lwt_main.ml", line 31, characters 10-20
Called from Lwt_main.run in file "src/unix/lwt_main.ml", line 118, characters 8-13
Re-raised at Lwt_main.run in file "src/unix/lwt_main.ml", line 124, characters 4-13
Called from Thread.create.(fun) in file "thread.ml", line 41, characters 8-14
Traceback (most recent call last):
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/tactician-ivSxM0/repo/src/py-src/nnserver.py", line 135, in <module>
    asyncio.run(main())
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/tactician-ivSxM0/repo/src/py-src/nnserver.py", line 125, in main
    server = await asyncio.start_server(
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 60710): address already in use
Thread 1 killed on uncaught exception Failure("Embedding.generateEmbedding: Failed: This vat has no restorer")
Raised at Lwt.Miscellaneous.poll in file "src/core/lwt.ml", line 3072, characters 20-29
Called from Lwt_main.run.run_loop in file "src/unix/lwt_main.ml", line 31, characters 10-20
Called from Lwt_main.run in file "src/unix/lwt_main.ml", line 118, characters 8-13
Re-raised at Lwt_main.run in file "src/unix/lwt_main.ml", line 124, characters 4-13
Called from Thread.create.(fun) in file "thread.ml", line 41, characters 8-14
Traceback (most recent call last):
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/tactician-ivSxM0/repo/src/py-src/nnserver.py", line 135, in <module>
    asyncio.run(main())
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/tactician-ivSxM0/repo/src/py-src/nnserver.py", line 125, in main
    server = await asyncio.start_server(
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 53210): address already in use
Thread 1 killed on uncaught exception Failure("Embedding.generateEmbedding: Failed: This vat has no restorer")
Raised at Lwt.Miscellaneous.poll in file "src/core/lwt.ml", line 3072, characters 20-29
Called from Lwt_main.run.run_loop in file "src/unix/lwt_main.ml", line 31, characters 10-20
Called from Lwt_main.run in file "src/unix/lwt_main.ml", line 118, characters 8-13
Re-raised at Lwt_main.run in file "src/unix/lwt_main.ml", line 124, characters 4-13
Called from Thread.create.(fun) in file "thread.ml", line 41, characters 8-14
Traceback (most recent call last):
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/tactician-ivSxM0/repo/src/py-src/nnserver.py", line 135, in <module>
    asyncio.run(main())
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/tactician-ivSxM0/repo/src/py-src/nnserver.py", line 125, in main
    server = await asyncio.start_server(
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/tmp/tactician-ivSxM0/envs/coq-tactician-graph/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 45074): address already in use
