WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 686, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 370, in main_loop
    predict.compute_new_definitions([cluster_state])
  File "/home/fidels/graph2tac/graph2tac/tfgnn/predict.py", line 284, in compute_new_definitions
    definition_embeddings = self.definition_task(scalar_definition_graph).flat_values
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fidels/graph2tac/graph2tac/tfgnn/tasks.py", line 731, in call
    embedded_graph = self._graph_embedding(bare_graph, training=training)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/site-packages/tensorflow_gnn/keras/layers/map_features.py", line 227, in call
    node_set_features[node_set_name] = _call_model(
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/site-packages/tensorflow_gnn/keras/layers/map_features.py", line 285, in _call_model
    return model(graph_piece)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer "graph_embedding_node_embedding" (type Embedding).

indices[0] = 1033 is not in [0, 1031) [Op:ResourceGather]

Call arguments received by layer "graph_embedding_node_embedding" (type Embedding):
  â€¢ inputs=tf.Tensor(shape=(3,), dtype=int64)
File "./theories/Init/Logic.v", line 69, characters 4-24:
Error: Anomaly "Capnp protocol error 1"
Please report at http://coq.inria.fr/bugs/.

