Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 684, in main
    with Path(args.exclude_tactics).open('r') as yaml_file:
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '~/data/mini_stdlib_always_none.yml'
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 684, in main
    with Path(args.exclude_tactics).open('r') as yaml_file:
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '~/data/mini_stdlib_always_none.yml'
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 684, in main
    with Path(args.exclude_tactics).open('r') as yaml_file:
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '~/data/mini_stdlib_always_none.yml'
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 684, in main
    with Path(args.exclude_tactics).open('r') as yaml_file:
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '~/data/mini_stdlib_always_none.yml'
File "./theories/Init/Logic.v", line 111, characters 4-46:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 74, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 106, characters 4-16:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 69, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

