Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 659, in main
    os.environ['G2T_LOG_LEVEL'] = log_levels[args.log_level]
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
File "./theories/Init/Logic.v", line 69, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 74, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

