WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 270, in main_loop
    logger.info(f'theorem {context_cnt} had {msg_idx} '
Message: 'theorem 0 had 1 messages received of total size (unpacked) 12200 bytes, with network compiled in 0.012524 s, '
Arguments: ('with 3 def clusters updated in 3.973410 s',)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.999997'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.000002'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.999997'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.000002'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 1.000000'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 270, in main_loop
    logger.info(f'theorem {context_cnt} had {msg_idx} '
Message: 'theorem 1 had 3 messages received of total size (unpacked) 13080 bytes, with network compiled in 0.008753 s, '
Arguments: ('with 4 def clusters updated in 2.540733 s',)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.775621'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.224379'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.775621'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.224379'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.775621'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.224379'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 270, in main_loop
    logger.info(f'theorem {context_cnt} had {msg_idx} '
Message: 'theorem 2 had 3 messages received of total size (unpacked) 19168 bytes, with network compiled in 0.001369 s, '
Arguments: ('with 1 def clusters updated in 0.605921 s',)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.916971'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.063278'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.017791'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.001960'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.916971'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.063278'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.017791'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.001960'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.867167'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.125430'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.007404'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.916971'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.063278'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.017791'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.001960'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.867167'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.125430'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.007404'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.916971'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.063278'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.017791'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.001960'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.867167'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.125430'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.007404'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.916971'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.063278'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.017791'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.001960'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.867167'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.125430'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.007404'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.968779'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.021143'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.010059'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000018'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.863191'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.129889'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.006920'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.999999'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.000001'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.000000'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000000'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 0, prob = 0.956155'
Arguments: (array([[        0, 848769603]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 1, prob = 0.043362'
Arguments: (array([[       0, 90848472]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 2, prob = 0.000413'
Arguments: (array([[        0, 898390247]], dtype=uint32),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/fidels/miniconda3/envs/graph2tac/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 693, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 470, in main_loop
    logger.info(f"sending to coq the action {action_idx}, prob = {online_confidence:.6f}",
Message: 'sending to coq the action 3, prob = 0.000070'
Arguments: (array([[        0, 565191440]], dtype=uint32),)
