WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
WARNING:tensorflow:Mapping types may not work well with tf.nest. Prefer using MutableMapping for <class 'tensorflow_gnn.graph.graph_tensor._ImmutableMapping'>
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 688, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 223, in main_loop
    train_node_label_to_name = [bytes(s, 'utf8') for s in predict.get_label_to_name()]
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 688, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 223, in main_loop
    train_node_label_to_name = [bytes(s, 'utf8') for s in predict.get_label_to_name()]
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 688, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 223, in main_loop
    train_node_label_to_name = [bytes(s, 'utf8') for s in predict.get_label_to_name()]
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/fidels/miniconda3/envs/graph2tac/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac', 'console_scripts', 'g2t-server')())
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 688, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/home/fidels/graph2tac/graph2tac/loader/predict_server.py", line 223, in main_loop
    train_node_label_to_name = [bytes(s, 'utf8') for s in predict.get_label_to_name()]
TypeError: 'NoneType' object is not iterable
File "./theories/Init/Logic.v", line 106, characters 4-16:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 69, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 74, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Logic.v", line 111, characters 4-46:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

