  Running command git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac.git /tmp/pip-req-build-dhmir4nd
  Running command git rev-parse -q --verify 'sha^8ba2f1634fb25aeb5da90a4e5840eee964cc0e19'
  Running command git fetch -q https://github.com/IBM/graph2tac.git 8ba2f1634fb25aeb5da90a4e5840eee964cc0e19
  Running command git checkout -q 8ba2f1634fb25aeb5da90a4e5840eee964cc0e19
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/coq-tactician/coq-tactician-reinforce' /tmp/pip-install-7sip97br/pytactician_16f22e6feb6344cfb532aebf85c0dc58
  Running command git rev-parse -q --verify 'sha^623952029b0b5e997c08634ba09bb549a0015a0a'
  Running command git fetch -q 'https://****@github.com/coq-tactician/coq-tactician-reinforce' 623952029b0b5e997c08634ba09bb549a0015a0a
  Running command git checkout -q 623952029b0b5e997c08634ba09bb549a0015a0a
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      kj/filesystem-disk-unix.c++:1734: warning: PWD environment variable doesn't match current directory; pwd = /home/lasse/Documents/Projects/Tactician/benchmark-system/tmp-scratch/target-source
      kj/filesystem-disk-unix.c++:1734: warning: PWD environment variable doesn't match current directory; pwd = /home/lasse/Documents/Projects/Tactician/benchmark-system/tmp-scratch/target-source
      kj/filesystem-disk-unix.c++:1734: warning: PWD environment variable doesn't match current directory; pwd = /home/lasse/Documents/Projects/Tactician/benchmark-system/tmp-scratch/target-source
      Traceback (most recent call last):
        File "/tmp/pip-install-7sip97br/pytactician_16f22e6feb6344cfb532aebf85c0dc58/./pytact/generate_api.py", line 18, in <module>
          capnp.add_import_hook(include_dir)
      TypeError: capnp.lib.capnp.add_import_hook() takes no arguments (1 given)
      ./pytact/generate_api.py: plugin failed: exit code 1
      b''
      Traceback (most recent call last):
        File "/home/lasse/Documents/Projects/Tactician/benchmark-system/tmp-scratch/target-source/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lasse/Documents/Projects/Tactician/benchmark-system/tmp-scratch/target-source/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lasse/Documents/Projects/Tactician/benchmark-system/tmp-scratch/target-source/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-typbka9h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-typbka9h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-typbka9h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 42, in <module>
        File "<string>", line 22, in capnp2cython
        File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['capnpc', '-o./pytact/generate_api.py', 'pytact/graph_api.capnp']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
