File "./theories/Init/Tactics.v", line 189, characters 0-45:
Warning:
now idtac((TacAlias Coq.Init.Tactics.now_#_62200C10 ((TacThen (TacArg (CAst (Reference (CAst t)))) (TacArg (CAst (TacCall Coq.Init.Tactics.easy (CAst Located)))))) (CAst (Tacexp (TacId)))))
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
    from graph2tac.loader.predict_server import main
    from graph2tac.loader.predict_server import main
    from graph2tac.loader.predict_server import main
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
    from graph2tac.loader.predict_server import main
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
File "./theories/Init/Specif.v", line 230, characters 7-31:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Datatypes.v", line 78, characters 2-42:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Tactics.v", line 206, characters 2-26:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Peano.v", line 49, characters 2-21:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
    from graph2tac.loader.predict_server import main
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
    from graph2tac.loader.predict_server import main
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
File "./theories/Init/Logic.v", line 69, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Specif.v", line 234, characters 7-31:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
    from graph2tac.loader.predict_server import main
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/blaaulas/.local/bin/g2t-server", line 5, in <module>
    from graph2tac.loader.predict_server import main
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 15, in <module>
    from graph2tac.loader.data_server import DataServer, build_def_index, get_global_def_table, FILE_MULTIPLIER
  File "/home/blaaulas/.local/lib/python3.9/site-packages/graph2tac/loader/data_server.py", line 26, in <module>
    from graph2tac.loader.clib.loader import (
ImportError: libkj-0.7.0.so: cannot open shared object file: No such file or directory
File "./theories/Init/Logic.v", line 74, characters 4-24:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Init/Byte.v", line 815, characters 7-33:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

