File "./theories/Programming/Show.v", line 64, characters 2-37:
Warning: Declaring a scope implicitly is deprecated; use in advance an
explicit "Declare Scope show_scope.". [undeclared-scope,deprecated]
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 660, in main
    main_loop(reader, sock, predict, args.debug_dir,
  File "/tmp/tactician.tmp.4IsFqJ/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/predict_server.py", line 478, in main_loop
    log_normal(f'theorem {context_cnt} had {msg_idx} '
TypeError: unsupported format string passed to NoneType.__format__
